### ISSUE TITLE
Audio recorded affected on some devices when 'configuration.providesAudioData' = true is used'.

### ISSUE THREAD

**Issue by hizzlehoff** [gorastudio-ceo/SCNRecorder#38] opened 2021-11-18 14:35 UTC
When using:

let configuration = ARWorldTrackingConfiguration()
configuration.providesAudioData = true
sceneView.session.run(configuration)

On some devices (like iPad pro and iPhone 12) the volume for recording using AVFoundation's AVAudioRecorder is dramatically reduced. If anyone knows a solution for this I'd be very grateful.

**Comment by v-grigoriev** [comment] 2022-07-26 12:12
There doesn't seem to be an answer yet and the issue is not related to SCNRecorder. Closing.

**Closed by v-grigoriev** 2022-07-26 12:12 UTC
